### ISSUE TITLE
poweranks breaks towny and other plugins that use permsissions

### ISSUE THREAD

**Issue by 418teapot2** [PowerNetworkHub/PowerRanks#75] opened 2023-05-20 17:22 UTC
the way how powerranks set permission makes it so that any other plugin that adds permissions just doesnt add permissions, this breaks towny, luckperms,permissionsex and MANY other plugins, developer fix this

for as long as this is an issue, and until the developer makes a patch that fixes this and you see that in the release notes: DO NOT USE THIS PLUGIN

**Comment by svenar-nl** [comment] 2023-05-20 17:27
Closed as duplicate of #60

**Closed by svenar-nl** 2023-05-20 17:27 UTC
